---
# tasks file for roles/onet_certificat_generate

# La création d'un certificat auto-signé se réalise en trois étapes :
#   * Création de la clé privée               : /etc/pki/tls/private/myServer.pem
#   * Création de la requête de certification : /etc/pki/tls/certs/myServer.csr
#   * Création du certificat                  : /etc/pki/tls/certs/myServer.crt

# @action stat # Teste si la clé privée existe déjà.
- name: Teste si la clé privée existe déjà
  stat:
    path: "/etc/pki/tls/private/{{ key_name }}"
  register: pem_exists_result

# @action community.crypto.openssl_privatekey # Generate an OpenSSL private key.
- name: Generate an OpenSSL private key (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: "/etc/pki/tls/private/{{ key_name }}"
    type: RSA
    size: 4096
  when: not pem_exists_result.stat.exists

# @action stat # Teste si la requête de certification existe déjà.
- name: Teste si la requête de certification existe déjà
  stat:
    path: "/etc/pki/tls/certs/{{ ansible_hostname }}.csr"
  register: csr_exists_result

# @action community.crypto.openssl_csr # Generate an OpenSSL Certificate Signing Request.
- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "/etc/pki/tls/certs/{{ ansible_hostname }}.csr"
    privatekey_path: "/etc/pki/tls/private/{{ key_name }}"
    common_name: "{{ ansible_fqdn }}"
  when: not csr_exists_result.stat.exists

# @action stat # Teste si le certificat existe déjà.
- name: Teste si le certificat existe déjà
  stat:
    path: "/etc/pki/tls/certs/{{ crt_name }}"
  register: crt_exists_result

# @action community.crypto.x509_certificate # Generate a self signed cerificate.
- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "/etc/pki/tls/certs/{{ crt_name }}"
    privatekey_path: "/etc/pki/tls/private/{{ key_name }}"
    csr_path: "/etc/pki/tls/certs/{{ ansible_hostname }}.csr"
    provider: selfsigned
  when: not crt_exists_result.stat.exists
