---
- hosts: 
    cyclope
  become: true
  gather_facts: yes

  vars:
    # @var quick_start: True pour bypasser certaines opérations comme le Unseal
    - quick_start: True

  environment:
    PB_NAME: "test"

  # roles:

  #   # @role onet.certificat-generate: Génération d'un certificat auto-signé.
  #   - role: onet.certificat-generate
  #     key_name: "{{ ansible_hostname }}.pem"
  #     crt_name: "{{ ansible_hostname }}.crt"
  #     tags:
  #       # @tag ssl # Mise en oeuvre de TLS
  #       - ssl

  tasks:

    # @action debug # Ansible env.
    - name: Ansible env.
      debug:
        var: ansible_env

    # @action debug # Ansible facts.
    - name: Ansible facts.
      debug:
        var: ansible_facts

    # @action debug # Ansible hostname.
    - name: Ansible hostname.
      debug:
        var: ansible_hostname

  tags:
    # @tag test # Test
    - server
    # @tag deploy # Automatisation du déploiement
    - deploy
